/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LoggerService_CONSTANTS_H
#define LoggerService_CONSTANTS_H

#include "LoggerService_types.h"

namespace LoggerCpp {

class LoggerServiceConstants {
 public:
  LoggerServiceConstants();

};

extern const LoggerServiceConstants g_LoggerService_constants;

} // namespace

#endif
