/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LoggerService_TYPES_H
#define LoggerService_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace LoggerCpp {

class LoggerException;

typedef struct _LoggerException__isset {
  _LoggerException__isset() : error_code(false), error_description(false) {}
  bool error_code :1;
  bool error_description :1;
} _LoggerException__isset;

class LoggerException : public ::apache::thrift::TException {
 public:

  LoggerException(const LoggerException&);
  LoggerException& operator=(const LoggerException&);
  LoggerException() : error_code(0), error_description() {
  }

  virtual ~LoggerException() throw();
  int32_t error_code;
  std::string error_description;

  _LoggerException__isset __isset;

  void __set_error_code(const int32_t val);

  void __set_error_description(const std::string& val);

  bool operator == (const LoggerException & rhs) const
  {
    if (!(error_code == rhs.error_code))
      return false;
    if (!(error_description == rhs.error_description))
      return false;
    return true;
  }
  bool operator != (const LoggerException &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LoggerException & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const throw();
};

void swap(LoggerException &a, LoggerException &b);

inline std::ostream& operator<<(std::ostream& out, const LoggerException& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
