// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Logger.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::LoggerCpp;

class LoggerHandler : virtual public LoggerIf {
 public:
  LoggerHandler() {
    // Your initialization goes here
  }

  void timestamp(const std::string& filename) {
    // Your implementation goes here
    printf("timestamp\n");
  }

  void get_last_log_entry(std::string& _return, const std::string& filename) {
    // Your implementation goes here
    printf("get_last_log_entry\n");
  }

  void write_log(const std::string& filename, const std::string& message) {
    // Your implementation goes here
    printf("write_log\n");
  }

  int32_t get_log_size(const std::string& filename) {
    // Your implementation goes here
    printf("get_log_size\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<LoggerHandler> handler(new LoggerHandler());
  shared_ptr<TProcessor> processor(new LoggerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

