/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LoggerService_constants.h"

namespace LoggerCpp {

const LoggerServiceConstants g_LoggerService_constants;

LoggerServiceConstants::LoggerServiceConstants() {
}

} // namespace

